import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "./components/ui/sonner";
import { Providers } from "./providers";
import QueryProvider from "./components/query-provider";

const poppins = Poppins({
  variable: "--font-poppins",
  //subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Dental Office Online Scheduling System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <QueryProvider>
          <Providers>
            {children}
            <Toaster richColors closeButton />
          </Providers>
        </QueryProvider>
      </body>
    </html>
  );
}
